controllers:
  resource: ../src/Controller/
  type: annotation
# index:
#   path: /whatever
#   controller: App\Controller\MixedTapesController::homepage

kernel:
  resource: ../src/Kernel.php
  type: annotation
